apiVersion: v1
kind: Template
labels:
  template: label node dedicated to Alpha Corp
metadata:
  name: label node dedicated to Alpha Corp
objects:
- apiVersion: v1
  kind: Node
  metadata:
    labels:
      beta.kubernetes.io/arch: amd64
      beta.kubernetes.io/os: linux
      client: alpha
      runtime: docker
    name: "node1.${GUID}.internal"
parameters:
- description: Environmnet ID for OpenShift Homework
  name: GUID
  required: true
