apiVersion: v1
kind: Template
labels:
  template: label_alpha_corp_node
metadata:
  name: label node dedicated to Alpha Corp
objects:
- apiVersion: v1
  kind: Node
  metadata:
    labels:
      client: alpha
    name: "node1.${GUID}.internal"
- apiVersion: v1
  kind: Node
  metadata:
    labels:
      client: beta
    name: "node2.${GUID}.internal"
parameters:
- description: Environmnet ID for OpenShift Homework
  name: GUID
  required: true
