apiVersion: v1
kind: List
items:
- kind: ProjectRequest
  apiVersion: v1
  labels:
    client: alpha
  metadata:
    annotations:
      openshift.io/node-selector: client=alpha
    name: alpha-corp
    creationTimestamp: null
  displayName: Alpha Corp
- kind: ProjectRequest
  apiVersion: v1
  labels:
    client: beta
  metadata:
    annotations:
      openshift.io/node-selector: client=beta
    name: beta-corp
    creationTimestamp: null
  displayName: Beta Corp
