apiVersion: v1
kind: List
items:
- kind: Namespace
  apiVersion: v1
  labels:
    client: alpha
  metadata:
    annotations:
      openshift.io/node-selector: client=alpha
      net.beta.kubernetes.io/network-policy: '{"ingress":{"isolation":"DefaultDeny"}}'
    name: alpha-corp
    creationTimestamp: null
  displayName: Alpha Corp
- kind: Namespace
  apiVersion: v1
  labels:
    client: beta
  metadata:
    annotations:
      openshift.io/node-selector: client=beta
      net.beta.kubernetes.io/network-policy: '{"ingress":{"isolation":"DefaultDeny"}}'
    name: beta-corp
    creationTimestamp: null
  displayName: Beta Corp
- kind: Namespace
  apiVersion: v1
  labels:
    client: common
  metadata:
    annotations:
      openshift.io/node-selector: client=beta
      net.beta.kubernetes.io/network-policy: '{"ingress":{"isolation":"DefaultDeny"}}'
    name: common
    creationTimestamp: null
  displayName: Unspecified Customers
- kind: Group
  apiVersion: v1
  metadata:
    labels:
      client: alpha
    name: alpha
    namespace: alpha-corp
  users:
  - amy
  - andrew
- apiVersion: v1
  kind: Group
  metadata:
    labels:
      client: beta
    name: beta
    namespace: beta-corp
  users:
  - brian
  - betty
- apiVersion: v1
  kind: Group
  metadata:
    labels:
      client: common
    name: common
    namespace: common
- apiVersion: authorization.openshift.io/v1
  groupNames:
  - alpha
  kind: RoleBinding
  metadata:
    name: edit
    namespace: alpha-corp
    selfLink: /apis/authorization.openshift.io/v1/namespaces/alpha-corp/rolebindings/edit
  roleRef:
    name: edit
  subjects:
  - kind: Group
    name: alpha
  userNames: null
- apiVersion: authorization.openshift.io/v1
  groupNames:
  - beta
  kind: RoleBinding
  metadata:
    name: edit
    namespace: beta-corp
    selfLink: /apis/authorization.openshift.io/v1/namespaces/alpha-corp/rolebindings/edit
  roleRef:
    name: edit
  subjects:
  - kind: Group
    name: beta
  userNames: null
- apiVersion: authorization.openshift.io/v1
  groupNames:
  - common
  kind: RoleBinding
  metadata:
    name: edit
    namespace: common
    selfLink: /apis/authorization.openshift.io/v1/namespaces/alpha-corp/rolebindings/edit
  roleRef:
    name: edit
  subjects:
  - kind: Group
    name: common
  userNames: null
