apiVersion: v1
kind: List
items:
- kind: Namespace
  apiVersion: v1
  labels:
    client: alpha
  metadata:
    annotations:
      openshift.io/node-selector: client=alpha
      net.beta.kubernetes.io/network-policy: '{"ingress":{"isolation":"DefaultDeny"}}'
    name: alpha-corp
    creationTimestamp: null
  displayName: Alpha Corp
# - kind: ProjectRequest
#   apiVersion: v1
#   labels:
#     client: alpha
#   metadata:
#     annotations:
#       openshift.io/node-selector: client=alpha
#       net.beta.kubernetes.io/network-policy: '{"ingress":{"isolation":"DefaultDeny"}}'
#     name: alpha-corp
#     creationTimestamp: null
#   displayName: Alpha Corp
- kind: ProjectRequest
  apiVersion: v1
  labels:
    client: beta
  metadata:
    annotations:
      openshift.io/node-selector: client=beta
      net.beta.kubernetes.io/network-policy: '{"ingress":{"isolation":"DefaultDeny"}}'
    name: beta-corp
    creationTimestamp: null
  displayName: Beta Corp
