apiVersion: v1
kind: Template
labels:
  template: alpha-corp-project
metadata:
  name: alpha-corp-project
objects:
- kind: ProjectRequest
  apiVersion: v1
  labels:
    client: alpha
  metadata:
    annotations:
      openshift.io/node-selector: client=alpha
    name: alpha-corp
    creationTimestam: null
  displayName: Alpha Corg
- apiVersion: networking.k8s.io/v1
  kind: NetworkPolicy
  metadata:
    name: allow-same-namespace
    namespace: alpha-corp
  spec:
    ingress:
    - from:
      - podSelector: {}
    - from:
      - namespaceSelector:
          matchLabels:
            name: alpha-corp
