---
- name: Deploy and Execute CICD workflow
  hosts: localhost
  tasks:
    - name: checkout Basic Spring Boot
      git:
        repo: https://github.com/redhat-cop/container-pipelines.git
        dest: container-pipelines
        version: v3.5.0
    - name: install Galaxy dependencies
      shell: ansible-galaxy install -r requirements.yml --roles-path=galaxy
      args:
        chdir: container-pipelines/basic-spring-boot
    - name: Deploy Basic Spring Boot with Ansible
      shell: ansible-playbook -i ./.applier/ galaxy/openshift-applier/playbooks/openshift-cluster-seed.yml
      args:
        chdir: container-pipelines/basic-spring-boot

