---
- name: create persistent volumes
  hosts: nfs
  tasks:
  - name: pvs creator
    with_sequence: start=1 end=200
    include_role:
      name: openshift-applier
    vars:
      openshift_cluster_content:
      - object: "PersistentVolume{{ item }}"
        content:
          - name: Create Persistent Volume
            template: templates/pv_template.yaml
            params_from_vars:
              volume_var: "{{ item }}"
