---
- name: setup support node
  hosts: nfs
  tasks:
  - name: create volume directories
    file:
      path: "/srv/nfs/user-vols/pv{{ item }}"
      group: nobody
      owner: nobody
      state: directory
      mode: '777'
    with_sequence: start=1 end=200
  - name: create /etc/exports.d/openshift-uservols.exports
    file:
      path: /etc/exports.d/openshift-uservols.exports
      state: touch
  - name: define exports
    lineinfile:
      path: /etc/exports.d/openshift-uservols.exports
      line: "/srv/nfs/user-vols/pv{{ item }} *(rw,root_squash)"
    with_sequence: start=1 end=200
  - name: restart nfs-server
    service:
      name: nfs-server
      state: restarted

- name: create PersistentVolume objects in the OpenShift cluster
  hosts: localhost
  tasks:
  - name: create 25 openshift templates with 5Gi PersistentVolume objects
    template:
      src: templates/pv_template.yaml
      dest: "resources/pv_template_5Gi_{{item}}.yaml"
    vars:
      GUID: "{{ lookup('env','GUID') }}"
      VOLUME: "{{ item }}"
      SIZE: 5Gi
    with_sequence: start=1 end=25
  - name: create PersistentVolume objects in cluster
    with_sequence: start=1 end=25
    include_role:
      name: openshift-applier
    vars:
      ansible_connection: local
      openshift_cluster_content:
      - object: PersistentVolume
        content:
          - name: Create 5Gi PersistentVolume objects in cluster
            action: create
            file: "resources/pv_template_5Gi_{{item}}.yaml"
  - name: create 25 openshift templates with 10Gi PersistentVolume objects
    template:
      src: templates/pv_template.yaml
      dest: "resources/pv_template_10Gi_{{item}}.yaml"
    vars:
      GUID: "{{ lookup('env','GUID') }}"
      VOLUME: "{{ item }}"
      SIZE: 10Gi
    with_sequence: start=26 end=50
  - name: create PersistentVolume objects in cluster
    with_sequence: start=26 end=50
    include_role:
      name: openshift-applier
    vars:
      ansible_connection: local
      openshift_cluster_content:
      - object: PersistentVolume
        content:
          - name: Create 10Gi PersistentVolume objects in cluster
            action: create
            file: "resources/pv_template_10Gi_{{item}}.yaml"
