---
- name: create persistent volumes
  hosts: localhost
  tasks:
  - name: create openshift templates with PersistentVolume objects
    template:
      src: templates/pv_template.yaml
      dest: "resources/pv_template_{{item}}.yaml"
    vars:
      GUID: "{{ lookup('env','GUID') }}"
      VOLUME: "{{ item }}"
    with_sequence: start=1 end=2
  - name: create PersistentVolume objects in cluster
    with_sequence: start=1 end=2
    include_role:
      name: openshift-applier
    vars:
      ansible_connection: local
      openshift_cluster_content:
      - object: "PersistentVolume{{ item }}"
        content:
          - name: Create Persistent Volume
            file: "resources/pv_template_{{item}}.yaml"
