---
- name: create persistent volumes
  hosts: nfs
  roles:
    - openshift-applier
      vars:
        openshift_cluster_content:
        - object: PersistentVolume
          content:
            - name: Create Persistent Volume
              template: templates/pv_template.yaml
      with_sequence: start=1 end=200
