---
- name: Deploy multitenant environments
  hosts: localhost
  tasks:
    - name: prepare parameter for node labelling
      lineinfile:
        path: resources/multitenant/parames/nodes
        regexp: 'GUID=.*$'
        line: "GUID={{GUID}}"
    - name: Deploy 2 customers Alpha Corp and Beta Corp
      include_role:
        name: openshift-applier
      vars:
        openshift_cluster_content:
        - object: projects
          content:
          - name: Create environments with users and groups
            file: resources/multitenant/templates/projects.yaml
            action: create
        - object: node labels
          content:
          - name: label nodes dedicated to each customer
            template: resources/multitenant/templates/node_labels.yaml
            params: resources/multitenant/params/nodes
  vars:
    ansible_connection: local

