---
- name: Deploy multitenant environments
  hosts: localhost
  tasks:
    - name: Deploy 2 customers Alpha Corp and Beta Corp
      include_role:
        name: openshift-applier
      vars:
        openshift_cluster_content:
        - object: projects
          content:
          - name: Create environments with users and groups
            file: resources/multitenant/templates/projects.yaml
            action: create
        - object: node labels
          content:
          - name: label nodes dedicated to each customer
            template: resources/multitenant/templates/node_labels.yaml
            params_from_vars:
              GUID: "{{ GUID }}"
        # - object: network policies
        #   content:
        #   - name: define network policies
        #     description: |-
        #       create a network policy for each project to allow
        #       communication between project's pods
        #     template: resources/multitenant/templates/netpolicy.yaml
        #     action: create
  vars:
    ansible_connection: local

