---
- name: Update default template
  hosts: localhost
  tasks:
    - name: get bootstrap-project template
      shell: oc adm create-bootstrap-project-template -o yaml > template.yaml
    - name: add default annotation to deny all
      replace:
        path: template.yaml
        regexp: '(kind: Project\s*\n\s*metadata:\s*\n\s*annotations:)'
        replace: '\1\n      net.beta.kubernetes.io/network-policy: ''{"ingress":{"isolation":"DefaultDeny"}}'''
    - name: add network policy items to the template
      lineinfile:
        path: template.yaml
        insertbefore: "parameters:"
        line: |-
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-same-and-default-namespace
            spec:
              ingress:
              - from:
                - podSelector: {}
              - from:
                - namespaceSelector:
                    matchLabels:
                      name: default
    - name: create project-request template
      include_role:
        name: openshift-applier
      vars:
        openshift_cluster_content:
        - object: project-request template
          content:
          - name: create project-request template
            file: template.yaml
            action: create
            namespace: default
  vars:
    ansible_connection: local

- name: Update master-config on all master nodes
  hosts: masters
  tasks:
    - name: set