---
- name: Update default template
  hosts: localhost
  tasks:
    - name: get bootstrap-project template
      shell: oc adm create-bootstrap-project-template -o yaml > template.yaml
    - name: add default annotation to deny all traffic to in project
      replace:
        path: template.yaml
        regexp: '(kind: Project\s*\n\s*metadata:\s*\n\s*annotations:\s*\n)((^\s+\S*\n)*)(?!net.beta.kubernetes.io/network-policy)(.*\n)'
        replace: '\1      net.beta.kubernetes.io/network-policy: ''{"ingress":{"isolation":"DefaultDeny"}}''\n\2'
    - name: add network-policy to allow project internal communication between pods
      blockinfile:
        path: 1_bootstrap_template.yaml
        insertbefore: "parameters:"
        block: |-
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-same-and-default-namespace
            spec:
              ingress:
              - from:
                - podSelector: {}
              - from:
                - namespaceSelector:
                    matchLabels:
                      name: default
    - name: create new project-request template in 'default' namespace
      include_role:
        name: openshift-applier
      vars:
        openshift_cluster_content:
        - object: project-request template
          content:
          - name: create project-request template
            file: template.yaml
            action: create
            namespace: default
  vars:
    ansible_connection: local

- name: Update master-config on all master nodes
  hosts: masters
  tasks:
    - name: point project-request template to 'default/project-request' template
      lineinfile:
        path: /etc/origin/master/master-config.yaml
        regexp: "projectRequestTemplate"
        line: "  projectRequestTemplate: \"default/project-request\""
    - name: restart control-plane pods
      shell: /usr/local/bin/master-restart api; /usr/local/bin/master-restart controllers
