---
- name: Update default template
  hosts: localhost
  tasks:
    - name: get bootstrap template
      shell: oc adm create-bootstrap-project-template -o yaml > template.yaml
    - name: add network policy items to the template
      lineinfile:
        path: template.yaml
        insertbefore: "parameters:"
        line: |-
          - apiVersion: networking.k8s.io/v1
            kind: NetworkPolicy
            metadata:
              name: allow-same-and-default-namespace
            spec:
              ingress:
              - from:
                - podSelector: {}
              - from:
                - namespaceSelector:
                    matchLabels:
                      name: default
    - name: add default annotation to deny all
      lineinfile:
        path: template.yaml
        insertafter: "(?s)kind: Project.*?annotations:"
        line: |-
          net.beta.kubernetes.io/network-policy='{"ingress":{"isolation":"DefaultDeny"}}'
  vars:
    ansible_connection: local