apiVersion: v1
kind: "PersistentVolume"
metadata:
  name: "pv{{ VOLUME }}"
spec:
  capacity:
      storage: "{{ SIZE }}"
  accessModes: [ "ReadWriteOnce" ]
  nfs:
    path: "/srv/nfs/user-vols/pv{{ VOLUME }}"
    server: "support1.{{ GUID }}.internal"
  persistentVolumeReclaimPolicy: "Recycle"
