apiVersion: "v1"
kind: "PersistentVolume"
metadata:
  name: "{{ volume_var }}"
spec:
  capacity:
      storage: "10Gi"
  accessModes: [ "ReadWriteOnce" ]
  nfs:
    path: "/srv/nfs/user-vols/{{ volume_var }}"
    server: "support1.{{ GUID }}.internal"
  persistentVolumeReclaimPolicy: "Recycle"
